### ISSUE TITLE
Develop application profile

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap.prototype#1]
See https://wiki1.hbz-nrw.de/x/vI6f.

**Comment by trugwaldsaenger** [comment]
I just discussed with acka47 that it might be a good idea to include repositories into the application profile as well, since they are the link to the ressources.

**Comment by acka47** [comment]
I already addressed the question in the AP draft and I Agree that repositories should be handled as first class entities, already in the resources. (Otherwise, I'd have described them using blank nodes.)

**Comment by acka47** [comment]
I think the application profilem is quite mature now and can be used for further work, see https://wiki1.hbz-nrw.de/x/vI6f. (Actually, @dr0i is already using it for the transformation.
schema.org turned out to be sufficient for most of the information we need. The profile contains three properties and one class from four different additional vocabs, though (dcterms:license, marcrel:fnd, org:OrganizationalCollaboration and openorg:contact).

**Comment by acka47** [comment]
The human-readable description of this AP is finished for now, thus closing this ticket. A formal description of the AP in RDF including some more information will also be developed, see #7.
