### ISSUE TITLE
Add attribution of GeoNames

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap.prototype#100]
We use GeoNames data in API and Drupal frontend. The data is licensed under a [CC-BY](http://creativecommons.org/licenses/by/3.0/) license which means attribution should be given when reusing the data.

[Here](http://www.geonames.org/export/) it reads:

> cc-by licence (creative commons attributions license). You should give credit to GeoNames when using data or web services with a link or another reference to GeoNames. 

I suggest to add the following text to the [API page](http://lobid.org/oer):

> ## Credit
> 
> This API includes [GeoNames](http://www.geonames.org/) data licensed under [CC-BY 3.0](http://creativecommons.org/licenses/by/3.0/). 

@literarymachine : You might add a similar note to oerworldmap.org, e.g.:

> This service makes use of [GeoNames](http://www.geonames.org/) data licensed under [CC-BY 3.0](http://creativecommons.org/licenses/by/3.0/).

**Comment by fsteeg** [comment]
Deployed to production, closing: http://api.lobid.org/oer
