### ISSUE TITLE
Implement query routes for initial data set

### ISSUE THREAD

**Issue by fsteeg** [hbz/oerworldmap.prototype#11]
Basic idea: a single `/oer` route with `type=` filters for different entities.

Note: the query parameter has to be implemented as `t=`, with a rewrite rule in the Apache config.

**Comment by fsteeg** [comment]
Basic query route and API documentation deployed, closing. See http://staging.api.lobid.org/oer.

**Comment by acka47** [comment]
When I query for http://staging.api.lobid.org/oer?q=*&t=http://schema.org/Service I get resources typed `schema:CollegeOrUniversity` which is not correct.
