### ISSUE TITLE
Create URI based on UUID

### ISSUE THREAD

**Issue by dr0i** [hbz/oerworldmap.prototype#17]
In https://github.com/hbz/oerworldmap/issues/5#issuecomment-36109604 @acka47 states that we want URIs  based on a UUID.
UUIDs are great to create a new resource, but require a lookup each time data is transformed which lacks these UUIDs as it is true for all the initial data coming from the different sources (ocwc etc.).
What must be done:  store a link in the transformed data to be able to make lookups.
@acka47 : is 
       `<uuid>` `<dc:identifier>` "$ocwcID" .
good enough?

**Comment by acka47** [comment]
I think it is ok for now to use dc:identifier for internal purposes, adding a prefix for the respective service the ID stems from (e.g. ocwc).

**Comment by fsteeg** [comment]
Initial data with UUIDs is deployed to staging, see e.g.

http://staging.api.lobid.org/oer/7eee69cb-a218-4bbe-b6c3-5bb0c75cf4ad

Ping @literarymachine (cc @dr0i)

**Comment by literarymachine** [comment]
OK, so the URI-Structure is `http://staging.api.lobid.org/oer/{UUID}`. Now when I get the data, the URIs in there have the structure `http://oerworldmap.org/oer/{UUID}`. With this being so, a client has to isolate the UUIDs from the latter URI-structure in order to get information about a linked resource. I don't think that that is good. Since we are doing linked data, isn't the full HTTP-URI the actual identifier? As such, shouldn't it be used to request data from the API like so: `http://staging.api.lobid.org/oer/{http://oerworldmap.org/oer/{UUID}}`?

**Comment by acka47** [comment]
As in lobid we should only use URLs with parameters in the API. In this case:
http://staging.api.lobid.org/oer?id=7eee69cb-a218-4bbe-b6c3-5bb0c75cf4ad
Felix' use case should — as in lobid — also be supported:
http://staging.api.lobid.org/oer?id=http://oerworldmap.org/oer/7eee69cb-a218-4bbe-b6c3-5bb0c75cf4ad%22

**Comment by dr0i** [comment]
+1 . And then we should make http://oerworldmap.org/oer/7eee69cb-a218-4bbe-b6c3-5bb0c75cf4ad%22 resolvable to have linked data.

**Comment by literarymachine** [comment]
Yes, we should. And probably it should be the Drupal-frontend running on that Domain. As soon as @trugwaldsaenger sends me the login, I will point http://oerworldmap.org to my server.

**Comment by literarymachine** [comment]
> http://staging.api.lobid.org/oer/7eee69cb-a218-4bbe-b6c3-5bb0c75cf4ad

This data is buggy. The first `@graph` contains both `@type` statements.

**Comment by fsteeg** [comment]
To keep track of our internal discussion: we'll use `lobid.org` as the domain name in the subject URIs.

This will result in resolvable IDs like http://lobid.org/oer/7eee69cb-a218-4bbe-b6c3-5bb0c75cf4ad

**Comment by dr0i** [comment]
re "two types": s. #47
re "resolvable IDs": s. #47

**Comment by fsteeg** [comment]
Deployed to staging: http://staging.api.lobid.org/oer/1f4269a9-0103-4d9f-913c-5f127a5dab88

**Comment by acka47** [comment]
+1
