### ISSUE TITLE
Implement mapper to create Drupal field instances

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap.prototype#18]
Based on `rdfs:domain` and `rdfs:subClassOf`òwl:Restriction`, field instances are created and attached to bundles

**Comment by literarymachine** [comment]
Deployed to http://oerworldmap.literarymachine.net/oerworldmap/add

**Comment by acka47** [comment]
I have a problem with understanding this task. Thus, I can't check whether it is actually implemented. @literarymachine, please elaborate.

**Comment by acka47** [comment]
@literarymachine explained to me via chat: In Drupal, 'fields' are like properties without domain and range "restrictions". 'Field instances' are like properties which are tied to specific domain, range etc.

**Comment by acka47** [comment]
:+1:
