### ISSUE TITLE
Implement Linked Data entity type for Drupal

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap.prototype#19]

**Comment by literarymachine** [comment]
Deployed to http://oerworldmap.literarymachine.net/oerworldmap/add

**Comment by acka47** [comment]
@literarymachine What does this mean? For future tickets, it would be good if you could add a short description from the beginning, so I better understand what you are doing.

**Comment by acka47** [comment]
After chatting with @literarymachine I do: :+1:
