### ISSUE TITLE
contact OCWC for structured member data

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap.prototype#3]

**Comment by acka47** [comment]
The OCW consortium people were very quick and supportive and @gandalfar pointed us to the OCW API(s).

> you can use GeoJSON data from here: 
> http://members.ocwconsortium.org/api/v1/address/list/geo/
> 
> http://members.ocwconsortium.org/api/v1/address/list/geo/?format=json
> 
> If you need course information, it's available as either Excel Export:
> 
> http://data.ocwconsortium.org/dbdump/
> or API: http://data.ocwconsortium.org/

We haven't found out yet how to get detailed organization data in addition to the geodata and again asked for help.

**Comment by jurecuhalev** [comment]
Here are possible URL's:
at the moment: https://github.com/ocwc/ocwc-members/blob/master/members/crm/urls_api.py
and: https://github.com/ocwc/ocwc-mainsite/blob/master/members/functions.php

I'll add the browsing interface, extra fields and documentation. But the above URL should allow you to start prototyping.

Here's also the data model that we can expose up to a certain point: https://github.com/ocwc/ocwc-members/blob/master/members/crm/models.py#L102

**Comment by acka47** [comment]
Thanks, @gandalfar,  that will work.

**GET list of OCW consortium members**

```
http://members.ocwconsortium.org/api/v1/organization/group_by/membership_type/list/?format=json
```

Response:

```
{

    "Institutions of Higher Education": [
        {
            "id": 372,
            "name": "AGH University of Science and Technology",
            "membership_type": "Institutional Members - DC",
            "membership_status": "Current",
            "associate_consortium": ""
        }, 
... 
    ],
"Associate Consortia": [

    {
        "id": 432,
        "name": "African Virtual University",
        "membership_type": "Associate Consortium Members",
        "membership_status": "Sustaining",
        "associate_consortium": ""
    },
...
    ],
"Organizational Members": [

    {
        "id": 472,
        "name": "9x9",
        "membership_type": "Organizational Members",
        "membership_status": "Current",
        "associate_consortium": ""
    },
...
    ],
    "Corporate Members": [
        {
            "id": 562,
            "name": "Cisco Systems Australia Pty Ltd",
            "membership_type": "Corporate Members - Basic",
            "membership_status": "Current",
            "associate_consortium": ""
        },
...
    ]
}
```

**GET details on member by member id**

```
http://members.ocwconsortium.org/api/v1/organization/view/$member_id/?format=json
```

Example:

```
http://members.ocwconsortium.org/api/v1/organization/view/372/?format=json
```

Example result:

```
{

    "id": 372,
    "name": "AGH University of Science and Technology",
    "membership_type": "Institutional Members - DC",
    "membership_status": "Current",
    "associate_consortium": "",
    "display_name": "AGH University of Science and Technology",
    "main_website": "http://www.agh.edu.pl",
    "ocw_website": "http://open.agh.edu.pl",
    "description": "AGH-UST, established on 20th October 1919, until 1949 known as the Academy of Mining, founded after long-lasting endearments which had started in 1782, the year when the Ore Commission was established, has been continuing the traditions of the Academy of Mining in Kielce (1816-1827), inaugurated by Stanis¡aw Staszic.\r\n\r\nThe University, being a technical school, serves the science and industry through educating students, the development of academic staff, as well as research and development. The University cherishes its traditions and educates its students to be honest and responsible people both at work, and as members of the society, according to its motto: \"Labore creata, labori et scientiae servio\"(Created in labour, I serve labour and science).",
    "logo_small_url": "logos/agh_nzw_s_en_1w_wbr_rgb_33cb56f60c3b5f38dd3205eb4d2e3f33.jpg"

}
```

**GET list of geo coordinates**

```
http://members.ocwconsortium.org/api/v1/address/list/geo/?format=json
```

 Result:

```
{
    "type": "FeatureCollection",
    "features": [
        {
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -72.2027326,
                    7.7926166
                ]
            },
            "type": "Feature",
            "id": 4,
            "properties": {
                "name": "Universidad Nacional Experimental del Táchira"
            }
        },
...
    ]
}
```

-> extract geo coordinates by searching for member id ("id").

**Comment by acka47** [comment]
For the logos, only a relative URL is provided 
(e.g. `"logos/agh_nzw_s_en_1w_wbr_rgb_33cb56f60c3b5f38dd3205eb4d2e3f33.jpg"`. 
The absolute URL looks like this:

```
http://members.ocwconsortium.org/media/logos/$filename
```

@gandalfar With adding absolute URLs you could easily make it easier for others to re-use (parts of) the data.

**Comment by jurecuhalev** [comment]
Detailed view is now returning 'logo_small_url', please use that URL as members will probably change as I move it behind https.

**Comment by acka47** [comment]
Thanks for the hint. I updated it in the comment and will tell @dr0i (who is working on the data transformations).

**Comment by dr0i** [comment]
@gandalfar thanks for the help! Just a remark - it would be most convenient if one could get _everything_ about an ID in _one record_ instead of making several API lookups. No joining then would be necessary etc.
