### ISSUE TITLE
Rename latitude and longitude properties

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap.prototype#33]
In order to use the geo-capabilities of elasticsearch, the keys `lat` and `lon` must be used instead of `latitude` and `longitude`: http://www.elasticsearch.org/blog/geo-location-and-search/

Pinging @acka47 and @dr0i since this affects the application profile and data transformation.

**Comment by fsteeg** [comment]
An option would be to internally create these values needed by Elasticsearch. The code that stores the incoming RDF in ES can get the location from the incoming data as it currently is, add the approprite format to allow the queries, and remove it before serving it as RDF again.

**Comment by literarymachine** [comment]
> An option would be to internally create these values needed by Elasticsearch.

I consider the API a black box, so as long as I get the functionality, I don't really care how it is implemented. What do @dr0i and @acka47 think about this?

**Comment by dr0i** [comment]
As I create RDF only, e.g. @acka47 could tell me how to model this with what properties:

```
"pin" : {
    "location" : {
        "lat" : 40.12,
        "lon" : -71.34
        }
```

If it is possible to do this somehow reasonable in RDF/JSON-LD I would vote do enhance the data as near at its source as it can be.

**Comment by literarymachine** [comment]
> The location element is a “geo enabled” location since it has lat and lon properties.
> -- http://www.elasticsearch.org/blog/geo-location-and-search/

We thus need `lat` and `lon` properties instead of `latitude` and `longitude` now. They can still be mapped to the same RDF predicate in the `@context`.

**Comment by acka47** [comment]
Using schema.org and the current @graph structure, the JSON-LD should currently look something like this:

```
"@graph": [
 {
        "@id": "http://oerworldmap.org/resource/ocw432",
        "@type": "http://schema.org/Organisation",
        geo": "_:b0"
     },
    {
        "@id": "_:b0",
        "@type": "http://schema.org/GeoCoordinates",
        "latitude": "-1.286577" ,
        "longitude": "36.8219367"
    }
]
```

If we'd use "nested" JSON-LD instead of the @graph structure, and would rename the "geo", "latitude" and "longitude" elements we'd get:

```
{
        "@id": "http://oerworldmap.org/resource/ocw432",
        "@type": "http://schema.org/Organisation",
        "location": {
            "@type": "http://schema.org/GeoCoordinates",
            "lat": "-1.286577",
            "lon": "36.8219367"
    }
```

Would this work for elasticsearch (ES)? One can see, that there is one level of hierarchy less than in the ES example. Also, the values have to be in quotes in JSON-LD. Does ES require this extra hierarchy level and the missing quotes? If so, we should certainly de-couple the internal data representation (which then enables geo search) from the data delivered via the API.

It would perhaps make sense in any ways to not make the delivered data dependent from what ES needs form certain features...

**Comment by acka47** [comment]
Ok, after writing this lenghty comment, I finally understood the problem and how easy the solution is. We will just have to adjust the (currently not existing) @context document to map the `schema:latitude` and `schema:longitude` to the JSON elements "lat" and "lon" and everything will be fine. Right?

**Comment by dr0i** [comment]
In former version of ES the "pin" hierarchy was mandatory. And I assume , so it is today. Not?

**Comment by dr0i** [comment]
Sorry - "location" is needed and be geo-point typed . "pin" is only the object.

**Comment by fsteeg** [comment]
I've deployed a version with the internal solution I suggested in https://github.com/hbz/oerworldmap/issues/33#issuecomment-37853493 to staging, see #37.

I'm not sure what the best solution would be. On the one hand, it would be nice to just store an retrieve the data and have it work. On the other hand, leaking details required for Elasticsearch to work into the API is not so nice. So maybe we just leave it as it is for now (internal solution).

@acka47 FYI, we actually do have a context: 
https://github.com/hbz/oerworldmap/blob/master/oer-api/public/data/context.json

**Comment by literarymachine** [comment]
+1

**Comment by acka47** [comment]
+1 from me too.

**Comment by dr0i** [comment]
+1
