### ISSUE TITLE
Implement Javascript map frontent

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap.prototype#39]

**Comment by literarymachine** [comment]
Primitive first version deployed to http://oerworldmap.literarymachine.net/oerworldmap

**Comment by acka47** [comment]
Here are some comments that come to my mind watching at the map. We might address some or all of these in future iterations.
- I think the map should be presented more prominently (=bigger). See for example http://openaccessmap.org/ We should think about removing the menu side bar on the left side.
- It may make sense to have different pins for the different resource types. (a person for person, building for organization or so etc.)
- Links to the oerworldmap resource description should be in the box that opens when clicking on a pin.
- And, of course, there's filter options to add (see #40, #57).

**Comment by dr0i** [comment]
looks nice! Experienced some minor issues, independent of browser (firefox, chrome,konqueror):
- pins seems to not fit exactly at lower zooming level: as zooming deeper into the map the pins seem to shift into proper position. E.g. the orange pin "person: Jörg Lohrer" starts somewhere north africa and shifting to Germany when zooming.
- opening an info box by clicking on a pin shifts the whole map (which is actually just a background and shouldn't shift at all IMO ) which I find confusing
- filter by "person" and by country "Germany" losses "person: Adrian Pohl". May be of some missing data?

I would want to support @acka47 wish to have a bigger map. Some issues, like the shifting of the map when opening an info box, may also be gone by this.

**Comment by literarymachine** [comment]
> pins seems to not fit exactly at lower zooming level: as zooming deeper into the map the pins seem to shift into proper position.

This issue seems to have crept in with the introduction of different markers. Will look into that.

> opening an info box by clicking on a pin shifts the whole map (which is actually just a background and shouldn't shift at all IMO ) which I find confusing

It was like that, shifting the map was (re-)introduced at the request of @acka47 and @trugwaldsaenger 

> filter by "person" and by country "Germany" losses "person: Adrian Pohl". May be of some missing data?

Indeed - the data only contained coordinates but no link to a country. After adding that link, the filter works as expected.

> I would want to support @acka47 wish to have a bigger map. Some issues, like the shifting of the map when opening an info box, may also be gone by this.

If time permits it, I will look into adding a larger map to the landing page.
