### ISSUE TITLE
Add primaryTopic to data

### ISSUE THREAD

**Issue by fsteeg** [hbz/oerworldmap.prototype#43]

**Comment by fsteeg** [comment]
Assigning to @dr0i for solution on data level.

This is related to our decision to use hashes instead of about pages. So the data should look like this:

```
<http://oerworldmap.org/oer/5e75df6e-84a0-4c57-b5f2-9bf47317ca8a#!> 
  <http://schema.org/name> 
  "The Open University of Israel" .
...
<http://oerworldmap.org/oer/5e75df6e-84a0-4c57-b5f2-9bf47317ca8a> 
  <http://xmlns.com/foaf/0.1/primaryTopic> 
  <http://oerworldmap.org/oer/5e75df6e-84a0-4c57-b5f2-9bf47317ca8a#!> .
```

The primaryTopic triples should end up in a file with the same name as the hash triples (here: ocwc1.nt)

**Comment by literarymachine** [comment]
I am currently trying to implement a generic lookup-solution for several endpoints. Geonames e.g. does not supply these triples, too. You can put this on hold, since I might get around the need.
