### ISSUE TITLE
Transform source data to application profile

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap.prototype#5]
We will focus on the OCW membership data and- if sensible - add data from other sources. For background and instructions see [application profile](https://wiki1.hbz-nrw.de/x/vI6f) and comments on #3 .

**Comment by acka47** [comment]
I took a look at the Serendipity map data from http://serendipity.utpl.edu.ec/map/data.php. There are only eight organizations described that aren't OCW consortium members (and thus described in the OCW member data). I created a gist with the JSON descriptions of these at https://gist.github.com/acka47/8952912 . (Don't know whether this is valid JSON...)

**Comment by dr0i** [comment]
I could also transform the serendipity data. But as this is based on wholly new data fields and so on I consider this to take +4 hours of work. Is ist wort this ?

**Comment by acka47** [comment]
The priority for these eight descriptions is low so you don't have to do anything about it. I may transform the data manually - e.g. by creating a JSON-LD context - in the future.

**Comment by dr0i** [comment]
ok, but be aware - the "ocw" id's of serendepity do not identify the same things as the ocwsconsortium id's. Don't mix them up.

**Comment by acka47** [comment]
### Example

This is a current example of the transformation:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://oerworldmap.org/resource/ocw404>
    <http://purl.org/dc/elements/1.1/identifier> "404" ;
    <http://schema.org/address> [
        <http://schema.org/addressLocality> "Cape Town", "City of Cape Town" ;
        <http://schema.org/schema:addressCountry> "South Africa" ;
        <http://schema.org/streetAddress> "Cross-Campus Road" ;
        <http://www.geonames.org/ontology#locatedIn> <http://sws.geonames.org/953987>
    ] ;
    <http://schema.org/description> "South African university" ;
    <http://schema.org/geo> [
        <http://schema.org/latitude> "-33.9550776" ;
        <http://schema.org/longitude> "18.4652802" ;
        a <http://schema.org/GeoCoordinates>
    ] ;
    <http://schema.org/logo> "http://www.ocwconsortium.org/media/logos/UCT online logo _ low res_7f3b3be1ecbd4e31763ff9ca6d9c6242.jpg" ;
    <http://schema.org/name> "University of Cape Town" ;
    <http://schema.org/providesService> <http://opencontent.uct.ac.za/> ;
    <http://schema.org/url> <http://www.uct.ac.za/> ;
    a <http://schema.org/CollegeOrUniversity> ;
    <http://www.w3.org/ns/org#hasMembership> <http://www.ocwconsortium.org/> .
```

### Comments

This already looks very good. I have the following comments and suggestions:
- The URI is not based on a uuid as we had aggreed upon.
- In the AP, I had replaced `org:hasMembership` by `schema:memberOf`. This isn't reflected in the data yet.
- schema:logo will be treated in the application as an owl:ObjectProperty with range foaf:Image. Thus, we'll need a URI instead of a literal in object position.
- We shouldn't use `gn:locatedIn` but put the country URI in  `schema:addressCountry`.
- The `schema:addressLocality` triple should be removed as it doesn't conform with the application profile that require a  `:Loacality` (subclass of `gn:Feature`).
- `schema:providesService` and `schema:memberOf` should not directly link to web resources but to oermap entites  of type `schema:Service`respectively `schema:Organization`. (E.g. http://oerworldmap.org/resource/ocw404 schema:memberOf http://oerworldmap.org/resource/ocwc .)
- Also, the data uses a property (`dct:identifier`) that isn't specified in the AP yet. When we really need it, I'd have to add it to the AP.

The output should look like this:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://lobid.org/oer/7eee69cb-a218-4bbe-b6c3-5bb0c75cf4ad#!>
    <http://purl.org/dc/elements/1.1/identifier> "ocwc404" ;
   <http://schema.org/memberOf> <$uuid-of-ocwc>
    <http://schema.org/address> [
        <http://schema.org/addressCountry> <http://sws.geonames.org/953987> ;
        <http://schema.org/streetAddress> "Cross-Campus Road" ;
    ] ;
    <http://schema.org/description> "South African university" ;
    <http://schema.org/geo> [
        <http://schema.org/latitude> "-33.9550776" ;
        <http://schema.org/longitude> "18.4652802" ;
        a <http://schema.org/GeoCoordinates>
    ] ;
    <http://schema.org/logo> "http://www.ocwconsortium.org/media/logos/UCT online logo _ low res_7f3b3be1ecbd4e31763ff9ca6d9c6242.jpg" ;
    <http://schema.org/name> "University of Cape Town" ;
    <http://schema.org/providesService> <http://lobid.org/oer/$uuid> ;
    <http://schema.org/url> <http://www.uct.ac.za/> ;
    a <http://schema.org/CollegeOrUniversity> ;
    <http://www.w3.org/ns/org#hasMembership> <http://www.ocwconsortium.org/> .

<http://lobid.org/oer/$uuid#!> 
    a schema:Service ;
    schema:provider <http://lobid.org/oer/7eee69cb-a218-4bbe-b6c3-5bb0c75cf4ad#!> ;
    schema:url <http://opencontent.uct.ac.za/> .
```

### Todo
- Discuss solution for implementing uuid-based URIs with bulk-loaded data.
- Replace `org:hasMembership` with `schema:memberOf`.
- Move geonames country URI to `schema:addressCountry`.
- Remove `schema:addressLocality` triples.
- Use schema:logo with logo URI in object position instead of a literal.
- Create a seperate entry for the OCWC where we can link to. (I'll provide this in another comment to this issue.)
- Create URIs and basic descriptions for services.
- Find a solution for services where we only have a URL and no name or description that we could add to the RDF. For now, we'd only have the triples seen above for a service.  Is this enough for the start? Could we somehow automatically get to `schema:name` or `schema:description`?

**Comment by literarymachine** [comment]
There is a bug in the address, `http://schema.org/schema:addressCountry` should read `http://schema.org/addressCountry` I believe.

**Comment by acka47** [comment]
Here's the RDF description of the OCWC itself:

```
@prefix schema: <http://schema.org/> .
@prefix org: <http://www.w3.org/ns/org#> .
@prefix gn: <http://www.geonames.org/ontology#> .

<http://lobid.org/oer/$ocwc-uuid>
    a org:OrganizationalCollaboration, schema:Organization ;
    schema:address [
        schema:addressLocality <http://sws.geonames.org/4945283/> ;
        schema:addressCountry <http://sws.geonames.org/6252001/> ;
        schema:postOfficeBoxNumber "02464";
    ] ;
    schema:description "The OpenCourseWare Consortium is a worldwide community of hundreds of higher education institutions and associated organizations committed to advancing open education and its impact on global education. " ;
    schema:logo "http://www.ocwconsortium.org/wp-content/themes/ocwc-mainsite/images/xlogo.png.pagespeed.ic.kzSPWsLJUE.jpg" ;
    schema:name "Open Courseware Consortium" ;
    schema:url <http://www.ocwconsortium.org/> ;
    schema:member <ocwc-member1> , <ocwc-member2> , ... .
```

**Comment by acka47** [comment]
By now, we have developed a quite mature version of an RDF application profile which currently resides at https://github.com/acka47/oerworldmap/blob/add-oer-ap/oerap.ttl. The results of the data transformation should comply with this AP.

E.g., @literarymachine found one violation of the AP: orgs from the OCWC data only have the rdf:type schema:CollegeOrUniversity which isn't given in the RDF AP. I guess, this could (and should) be fixed by also adding schema:Organization as type.

**Comment by acka47** [comment]
The application profile is now merged into the hbz/oerworldmap repo, see https://github.com/hbz/oerworldmap/blob/master/oerap.ttl. /@dr0i

**Comment by literarymachine** [comment]
As defined in the AP, the `addressCountry` property of a `PostalAddress` should not contain a literal, but a link to a `geonames:Feature`. This is not the case e.g. for `http://staging.api.lobid.org/oer/aa5c7dc0-a06e-4ada-9571-d9195bb3ca9a#!`.

```
http://schema.org/addressCountry: [
    "United Kingdom"
],
```

**Comment by literarymachine** [comment]
There is a dead link in the `memberOf` property of http://staging.api.lobid.org/oer/aa5c7dc0-a06e-4ada-9571-d9195bb3ca9a#! Also, the link should contain the fragment identifier `#!`.

```
http://schema.org/memberOf: [
    {
        @id: "http://lobid.org/oer/88feda8d-73bc-4b26-84be-f39687c31a04"
    }
],

$ curl http://lobid.org/oer/88feda8d-73bc-4b26-84be-f39687c31a04
[]
```

**Comment by dr0i** [comment]
sorry, yes, the UUID of the ocwc itself is for now just a placeholder - data
about the ocwc will be provided later.
As for the #! - you are right, gonna fix this.

**Comment by dr0i** [comment]
I created a separate issue regarding linking to services, s. : #62

**Comment by dr0i** [comment]
@acka47, you wrote: "Also, the data uses a property (dct:identifier) that isn't specified in the AP yet. When we really need it, I'd have to add it to the AP." 
So, yes, there is need of `dc:identifier` .
