### ISSUE TITLE
Add consortia and membership thereof to data

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap.prototype#53]
In the OCWC data many member descriptions indicate a membership in a consortium (found in the ocwc data's JSON key "associate_consortium"), e.g.:

```
{
    "id": 79,
    "name": "University of Tsukuba",
    "membership_type": "Institutional Members - MRC",
    "membership_status": "Current",
    "associate_consortium": "JOCWC"
}
```

It would be nice to also add links to the associate consortium into the RDF. Obviously, all of these consortia have also an entry in the OCWC JSON in the array "Associate Consortia".

Here is a list of the associate consortia that a currently mentioned in the OCWC JSON data along with their OCWC ID: 
- CCCOER ([448](http://members.ocwconsortium.org/api/v1/organization/view/448/?format=json))
- FOCW ([577](http://members.ocwconsortium.org/api/v1/organization/view/577/?format=json))
- JOCWC ([370](http://members.ocwconsortium.org/api/v1/organization/view/370/?format=json))
- KOCWC ([262](http://members.ocwconsortium.org/api/v1/organization/view/262/?format=json))
- TOCWC ([213](http://members.ocwconsortium.org/api/v1/organization/view/213/?format=json))
- Turkish OCWC ([214](http://members.ocwconsortium.org/api/v1/organization/view/214/?format=json))
- UNIVERSIA ([215](http://members.ocwconsortium.org/api/v1/organization/view/215/?format=json))
  ### To Do
- Add `schema:memberOf` and reciprocal `schema:member` links between the named consortia and their members as indicated in OCWC data.

**Comment by dr0i** [comment]
fyi, counted the links:
ocwc213=25, ocwc214=1, ocwc215=22, ocwc262=17, ocwc370=21, ocwc408=19, ocwc577=2

**Comment by dr0i** [comment]
Deployed to production, closing.
