### ISSUE TITLE
Make subject URI in API responses use the actual URL serving the response

### ISSUE THREAD

**Issue by fsteeg** [hbz/oerworldmap.prototype#55]
See https://github.com/hbz/oerworldmap/issues/48#issuecomment-38262017

Not so sure about this one. IMO the subject URIs (and resulting `@id` in the JSON-LD) should always be the same, since these are the entities we're talking about, independently of the host serving these.

**Comment by literarymachine** [comment]
There is no need for action in the course of this project here I think. But again, from a linked data point of view, I would favor and expect that `http://staging.api.lobid.org/oer/foo#!` delivers data about `http://staging.api.lobid.org/oer/foo#!`.

**Comment by acka47** [comment]
Closing. Project finished for some time now.
