### ISSUE TITLE
Link schema:providesService to oermap entities 

### ISSUE THREAD

**Issue by dr0i** [hbz/oerworldmap.prototype#62]
Taken from #5 by @acka47:
"`schema:providesService` should not directly link to web resources but to oermap entites of type schema:Service."
TODO:
- Create URIs and basic descriptions for services.
- Find a solution for services where we only have a URL and no name or description that we could add to the RDF. For now, we'd only have the triples seen above for a service. Is this enough for the start? Could we somehow automatically get to schema:name or schema:description?

roughly looks like:

```
<http://lobid.org/oer/$uuid#!> 
    a schema:Service ;
    schema:provider <http://lobid.org/oer/7eee69cb-a218-4bbe-b6c3-5bb0c75cf4ad#!> ;
    schema:url <http://opencontent.uct.ac.za/> .
```

**Comment by dr0i** [comment]
Deployed to staging:
organisation: http://staging.api.lobid.org/oer/3d9c8145-b059-43dd-9a47-da51529c7dba#!
and its service: http://staging.api.lobid.org/oer/9d5336d5-e01f-4711-a94f-1e1cdc782cae#!

**Comment by literarymachine** [comment]
By looking at it, I give a +1. Actually testing it from within Drupal is once again not easy, see https://github.com/hbz/oerworldmap/issues/48#issuecomment-38262017 and https://github.com/hbz/oerworldmap/issues/55#issuecomment-38288590.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
