### ISSUE TITLE
Editing a person and submitting yields error

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap.prototype#68]
I have tried several times now to add address data to one of the ["Adrian Pohl" entries]() and got this error message several times:

> Unable to PUT http://lobid.org/oer/d8693529-6797-48e1-b65d-8b2e7f1df77c#!
> EntityMalformedException: Missing bundle property on entity of type lde. in entity_extract_ids() (line 7721 of /home/fo/www/drupal-7.25/includes/common.inc).

**Comment by acka47** [comment]
Here is how the editing form looks like before submission and getting the error response:

![Submission to error](https://copy.com/va1C8NaAeNzgrUif/editing-error.png?download=1)

**Comment by acka47** [comment]
I tried submitting again after editing [this entry](http://oerworldmap.literarymachine.net/oerworldmap/resource/http%25253A%25252F%25252Flobid.org%25252Foer%25252F2e393e11-a402-42e0-a892-77766327100c%252523%252521). This resulted in creating [another "Adrian Pohl" entry](http://lobid.org/oer/b89761c4-ecbd-4d88-b4b6-717e847707ff#!) - with no address information...

**Comment by acka47** [comment]
The problem seems to be with the "country". I managed to add the other data but the error continues to show up when I try to add a country.

**Comment by literarymachine** [comment]
I believe this is an API issue, see #73 ping @fsteeg

**Comment by fsteeg** [comment]
Should work now, see https://github.com/hbz/oerworldmap/issues/73#issuecomment-38799418
