### ISSUE TITLE
Create formal description of application profile

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap.prototype#7]
including optional/obligatory/repeatable status of elements, labels for presentation in web form/results and prsentation order.

**Comment by acka47** [comment]
I will build on https://wiki1.hbz-nrw.de/x/aIaf for this and also draft an application profile vocabulary.

**Comment by acka47** [comment]
See http://wiki.dublincore.org/index.php/OER-world-map for general requirements of an RDF application profile. Please add corrections and suggestions here as you probably have no login for DCMI wiki.

**Comment by acka47** [comment]
See https://github.com/acka47/oerworldmap/blob/add-oer-ap/oerap.ttl for the current status of the application profile.

**Comment by literarymachine** [comment]
There is currently neither an `rdfs:range` nor an `owl:Restriction` for the `:license` and `:sameAs` properties, so that we cannot look up link targets (as a side note, I wouldn't even know where to look these up anyways).

**Comment by acka47** [comment]
Regarding `:license`: If we assume, that OER people exclusively choose CC licenses we could define the range as `cc:License`. (CC licenses have an RDF description typing the license as such, see e.g. rapper -i rdfa -o turtle http://creativecommons.org/publicdomain/zero/1.0/.).
Creating a lookup for CC licenses shouldn't be too time-consuming, though I think we shouldn't take care of this in the prototype.

Regarding `:sameAs`: It doesn't make sense to put restrictions on the type of the linked resource as we can't know to which data sources people may link and what the data in there looks like. That's why we can't provide a lookup for this.

At least, both properties are typed as `owl:ObjectProperty` so that people shouldn't be able to submit a string. (One could discuss whether this makes sense for `:license`...)

**Comment by literarymachine** [comment]
From a UI point of view does this mean that if the application profile contains an `owl:ObjectProperty`  that is not further defined, the editing form should contain a simple text field to put URIs in?

**Comment by acka47** [comment]
@literarymachine Exactly, the input should be validated against the HTTP URI scheme.

**Comment by acka47** [comment]
The application profile can now be found in the main oerworldmap repository at https://github.com/hbz/oerworldmap/blob/master/oerap.ttl.

**Comment by acka47** [comment]
The RDF AP exists and will only be adjusted slightly from now on.
