### ISSUE TITLE
Add all properties to context

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap.prototype#74]
The current `@context` ([1]) is lacking several properties: `http://schema.org/address`, `http://schema.org/memberOf`, `http://schema.org/addressCountry`, `http://schema.org/postalCode`, `http://schema.org/streetAddress`.

[1] https://github.com/hbz/oerworldmap/blob/master/oer-api/public/data/context.json

**Comment by fsteeg** [comment]
@acka47 Could you add these? Since you are more familiar with the data and the required JSON-LD `@type`s I think that would be the quicker way.
