### ISSUE TITLE
Transform WSIS data according to AP and add to index

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap.prototype#95]
See https://wiki1.hbz-nrw.de/x/kIGp.

**Comment by acka47** [comment]
I pre-processed the ugly csv data with open refine and placed the resulting data as json at https://github.com/hbz/oerworldmap/tree/issue-95-wsis/oer-data/src/main/resources/wsis. @dr0i is currently working on transforming it to RDF and adding GeoNames links as well as geo coordinates.

**Comment by dr0i** [comment]
In future, as we agreed, we should not make such big "container" issues. See the size of the corresponding pull request #101 - and it is far from its merging.

**Comment by dr0i** [comment]
Since #101 is merged this ticket is closed.
